/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-03-18 00:33:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>visitor header</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/footer.css\">\r\n");
      out.write("<script defer\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main/main-rank2.js\"></script>\r\n");
      out.write("<script defer\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main/mainbem.js\"></script>\r\n");
      out.write("<script defer\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main/mainclick.js\"></script>\r\n");
      out.write("<script defer\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main/mainnotice.js\"></script>\r\n");
      out.write("<script defer\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main/mainpro.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./app/basic/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\" main-banner\">\r\n");
      out.write("		<div class=\"main-outer\">\r\n");
      out.write("			<div id=\"banner-slider\" class=\"slider\">\r\n");
      out.write("				<div class=\"banner-item\">\r\n");
      out.write("\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/it-img2.jpg\"\r\n");
      out.write("						alt=\"Banner 1\" class=\"bannermall\"> <span\r\n");
      out.write("						class=\"banner-img-text\">Banner Text 1</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"banner-item\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/it-img3.jpg\"\r\n");
      out.write("						alt=\"Banner 2\" class=\"bannermall\"> <span\r\n");
      out.write("						class=\"banner-img-text\">Banner Text 2</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"banner-item\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/it-img6.jpg\"\r\n");
      out.write("						alt=\"Banner 3\" class=\"bannermall\"> <span\r\n");
      out.write("						class=\"banner-img-text\">Banner Text 3</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"banner-controls\">\r\n");
      out.write("				<main-clickbox-button class=\"banner-left\"> <img\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/arrow_left.png\"\r\n");
      out.write("					alt=\"main-clickbox-button 1\" class=\"bannerbtn\"> </main-clickbox-button>\r\n");
      out.write("				<main-clickbox-button class=\"banner-right\"> <img\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/arrow_right.png\"\r\n");
      out.write("					alt=\"main-clickbox-button 2\" class=\"bannerbtn\"> </main-clickbox-button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"main-container\">\r\n");
      out.write("			<div class=\"main-content-wrapper\">\r\n");
      out.write("				<!-- 랭킹 (왼쪽 상단) -->\r\n");
      out.write("\r\n");
      out.write("				<section class=\"main-ranking-body\">\r\n");
      out.write("					<div class=\"main-ranking-list\">\r\n");
      out.write("						<h1>명예의 전당</h1>\r\n");
      out.write("						<div class=\"main-ranking-container\" id=\"main-ranking-container\">\r\n");
      out.write("							<!-- js로 구현 -->\r\n");
      out.write("							<div id=\"context-path\" data-path=\"");
      out.print(request.getContextPath());
      out.write("\"></div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 메인 (랭킹 오른쪽에 위치) -->\r\n");
      out.write("				<!-- 이달의 Best Moon(질문) -->\r\n");
      out.write("				<section class=\"bestQ\">\r\n");
      out.write("				\r\n");
      out.write("					<h3>이달의 Best 질문</h3>\r\n");
      out.write("					<a id=\"bestMoonLink\" href=\"#\"> \r\n");
      out.write("					<span id=\"bestMoonTag\">카테고리</span>\r\n");
      out.write("						<div>\r\n");
      out.write("							<img src=\"./assets/img/best-que.png\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 id=\"bestMoonTitle\">게시물 제목</h4>\r\n");
      out.write("						<p id=\"bestMoonText\">이달의 베스트 질문 게시물 내용입니다.</p>\r\n");
      out.write("						<p>\r\n");
      out.write("						작성자 : <span id =\"bestMoonUserNick\"> 닉네임 없음</span>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/monitor.png\" alt=\"monitor\" class=\"monitor-icon\">\r\n");
      out.write("						<span id = \"bestMoonMonitor\" > 0 </span>						\r\n");
      out.write("						</p>\r\n");
      out.write("					</a>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이달의 Best 꿀팁 -->\r\n");
      out.write("				<section class=\"bestT\">\r\n");
      out.write("					<h3>이달의 Best 꿀팁</h3>\r\n");
      out.write("					<a id=\"bestTipLink\" href=\"#\">\r\n");
      out.write("					<span id=\"bestTipTag\">카테고리</span>\r\n");
      out.write("						<div>\r\n");
      out.write("							<img src=\"./assets/img/best-tip.png\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 id=\"bestTipTitle\">게시물 제목</h4>\r\n");
      out.write("						<p id=\"bestTipText\">이달의 베스트 꿀팁 게시물 내용입니다. </p>\r\n");
      out.write("						<p>\r\n");
      out.write("						작성자 : <span id =\"bestTipUserNick\"> 닉네임 없음</span>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/monitor.png\" alt=\"monitor\" class=\"monitor-icon\">\r\n");
      out.write("						<span id = \"bestTipMonitor\" > 0 </span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</a>\r\n");
      out.write("				</section>\r\n");
      out.write("				\r\n");
      out.write("				<script>\r\n");
      out.write("				console.log(window.location.pathname);\r\n");
      out.write("				document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("					fetch(window.location.pathname.includes('/AskIT_eend') \r\n");
      out.write("							? \"/AskIT_eend/bestArticles/mainBestArticles.main\" \r\n");
      out.write("							: \"/bestArticles/mainBestArticles.main\") // 컨트롤러에서 JSON 응답을 받음\r\n");
      out.write("				        .then(response => {\r\n");
      out.write("				            if (!response.ok) {\r\n");
      out.write("				                throw new Error(`서버 응답 오류 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${response.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("				            }	\r\n");
      out.write("				            return response.json();\r\n");
      out.write("				        })\r\n");
      out.write("				        .then(data => {\r\n");
      out.write("				            console.log(\"받은 데이터:\", data); // 디버깅용 출력\r\n");
      out.write("\r\n");
      out.write("				            if (data.bestMoon) {\r\n");
      out.write("				                document.getElementById(\"bestMoonTag\").textContent = data.bestMoon.articleBotCate || \"카테고리 없음\";\r\n");
      out.write("				                document.getElementById(\"bestMoonTitle\").textContent = data.bestMoon.articleTitle || \"제목 없음\";\r\n");
      out.write("				                document.getElementById(\"bestMoonText\").textContent = data.bestMoon.articleText || \"내용 없음\";\r\n");
      out.write("\r\n");
      out.write("				                document.getElementById(\"bestMoonUserNick\").textContent = data.bestMoon.userNick || \"닉네임 없음\";\r\n");
      out.write("				                document.getElementById(\"bestMoonMonitor\").textContent = data.bestMoon.articleMonitorNum || \"0\";\r\n");
      out.write("				             \r\n");
      out.write("				                document.getElementById(\"bestMoonLink\").href = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/detailAsk.dev?articleNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.bestMoon.articleNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("				            }\r\n");
      out.write("\r\n");
      out.write("				            if (data.bestTip) {\r\n");
      out.write("				                document.getElementById(\"bestTipTag\").textContent = data.bestTip.articleBotCate || \"카테고리 없음\";\r\n");
      out.write("				                document.getElementById(\"bestTipTitle\").textContent = data.bestTip.articleTitle || \"제목 없음\";\r\n");
      out.write("				                document.getElementById(\"bestTipText\").textContent = data.bestTip.articleText || \"내용 없음\";\r\n");
      out.write("\r\n");
      out.write("				                document.getElementById(\"bestTipUserNick\").textContent = data.bestTip.userNick || \"닉네임 없음\";\r\n");
      out.write("				                document.getElementById(\"bestTipMonitor\").textContent = data.bestTip.articleMonitorNum || \"0\";\r\n");
      out.write("				                \r\n");
      out.write("				                document.getElementById(\"bestTipLink\").href = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/detailAsk.dev?articleNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.bestMoon.articleNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("				            }\r\n");
      out.write("				        })\r\n");
      out.write("				        .catch(error => console.error(\"데이터 로딩 오류:\", error));\r\n");
      out.write("				});\r\n");
      out.write("</script>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!-- 메인 공지사항 -->\r\n");
      out.write("\r\n");
      out.write("	<section class=\"main-notice\">\r\n");
      out.write("		<div class=\"main-notice-head\">\r\n");
      out.write("			<main-clickbox-button class=\"main-notice-main-clickbox-button\"\r\n");
      out.write("				id=\"noticebutton\">공지사항</main-clickbox-button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"main-notice-body\">\r\n");
      out.write("			<div class=\"main-notice-list\">\r\n");
      out.write("				<div class=\"main-notice-item\" data-id=\"1\">\r\n");
      out.write("					<span class=\"main-notice-category\">공지</span> <span\r\n");
      out.write("						class=\"main-notice-title\">공지제목</span> <span\r\n");
      out.write("						class=\"main-notice-date\">2025-01-15</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"main-notice-item\" data-id=\"2\">\r\n");
      out.write("					<span class=\"main-notice-category\">공지</span> <span\r\n");
      out.write("						class=\"main-notice-title\">공지제목</span> <span\r\n");
      out.write("						class=\"main-notice-date\">2025-01-15</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"main-notice-item\" data-id=\"3\">\r\n");
      out.write("					<span class=\"main-notice-category\">공지</span> <span\r\n");
      out.write("						class=\"main-notice-title\">공지제목</span> <span\r\n");
      out.write("						class=\"main-notice-date\">2025-01-15</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 오늘의 랜덤 퀴즈 (랭킹 메인 아래 위치)-->\r\n");
      out.write("	<div class=\"main-pro-quiz-container\">\r\n");
      out.write("		<h3 class=\"main-pro-quiz-title\">오늘의 랜덤퀴즈!</h3>\r\n");
      out.write("		<div class=\"main-pro-quiz-box\">\r\n");
      out.write("			<p class=\"main-pro-quiz-question\">이건 뭘까요?</p>\r\n");
      out.write("			<button class=\"main-pro-answer-btn\" id=\"check-answer-btn\">문제풀기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 문제 모달 창 -->\r\n");
      out.write("	<div class=\"main-pro-modal\" id=\"quiz-modal\">\r\n");
      out.write("		<div class=\"main-pro-modal-content\">\r\n");
      out.write("			<p class=\"main-pro-modal-question\">Q.</p>\r\n");
      out.write("			<div class=\"main-pro-quiz-options\"></div>\r\n");
      out.write("\r\n");
      out.write("			<button class=\"main-pro-answer-btn\" id=\"show-answer-btn\">정답\r\n");
      out.write("				확인</button>\r\n");
      out.write("			<p id=\"pro-answer-dropdown\" style=\"display: none; margin-top: 10px;\"></p>\r\n");
      out.write("\r\n");
      out.write("			<button class=\"main-pro-modal-close-btn\" id=\"close-quiz-modal\">닫기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<button id=\"open-quiz-modal\"></button>\r\n");
      out.write("	<script>\r\n");
      out.write("        // 문제풀기 버튼 클릭 시 모달 창 열기\r\n");
      out.write("\r\n");
      out.write("        document\r\n");
      out.write("                .getElementById('check-answer-btn')\r\n");
      out.write("                .addEventListener(\r\n");
      out.write("                        'click',\r\n");
      out.write("                        function() {\r\n");
      out.write("                            document.getElementById('quiz-modal').style.display = 'flex';\r\n");
      out.write("                        });\r\n");
      out.write("        // 정답 확인 버튼 클릭 시 정답 표시\r\n");
      out.write("        document\r\n");
      out.write("                .getElementById('show-answer-btn')\r\n");
      out.write("                .addEventListener(\r\n");
      out.write("                        'click',\r\n");
      out.write("                        function() {\r\n");
      out.write("                            document.getElementById('pro-answer-dropdown').style.display = 'block'; // 정답 표시\r\n");
      out.write("                        });\r\n");
      out.write("        // 모달 닫기\r\n");
      out.write("        document\r\n");
      out.write("                .getElementById('close-quiz-modal')\r\n");
      out.write("                .addEventListener(\r\n");
      out.write("                        'click',\r\n");
      out.write("                        function() {\r\n");
      out.write("                            document.getElementById('quiz-modal').style.display = 'none';\r\n");
      out.write("                        });\r\n");
      out.write("    </script>\r\n");
      out.write("	<!-- 자격증(랜덤 퀴즈 아래 위치) -->\r\n");
      out.write("	<div class=\"main-clickbox\">\r\n");
      out.write("		<p class=\"main-title\">\r\n");
      out.write("			따고싶은 자격증이 있으신가요? 빠르게 <a href=\"./../article/qual/guide/infoSec.html\"\r\n");
      out.write("				class=\"main-date\">일정</a> 확인하세요!\r\n");
      out.write("		</p>\r\n");
      out.write("		<div class=\"main-clickbox\">\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">정보보안기사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">정보보안산업기사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">정보처리기사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">정보처리산업기사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">정보처리기능사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">리눅스\r\n");
      out.write("					마스터</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/qual/guide/infoPro.jsp\">네트워크관리사</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<p class=\"main-title\">\r\n");
      out.write("			관심있는 <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\"\r\n");
      out.write("				class=\"main-date\">태그</a>를 클릭해보세요!\r\n");
      out.write("		</p>\r\n");
      out.write("		<div class=\"main-clickbox main-interest\">\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">Java</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">HTML</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">CSS</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">JavaScript</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">Oracle</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/listAsk.dev\">Web</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/sec/ask.jsp\">Network</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/sec/ask.jsp\">Mobile</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/sec/ask.jsp\">포렌식</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-clickbox-button\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/article/sec/ask.jsp\">악성코드</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./app/basic/footer.jsp", out, false);
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
